#!/usr/bin/env python3
"""Start FlexivSimulation only."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

if str(Path(__file__).resolve().parent) not in sys.path:
    sys.path.insert(0, str(Path(__file__).resolve().parent))

import flexiv_runtime


def _relative_to_studio_root(path: Path, studio_root: Path) -> str:
    try:
        return str(path.relative_to(studio_root))
    except ValueError:
        return str(path)


def _find_one(paths: list[Path], *, description: str) -> Path:
    if not paths:
        raise FileNotFoundError(f"Could not find {description} in the Elements Studio simulator directory")
    return sorted(paths, key=lambda path: path.stat().st_mtime, reverse=True)[0]


def discover_simulation_assets(studio_root: Path) -> dict[str, str]:
    """Find the robot assets generated by Elements Studio for the active simulator."""
    root = Path(studio_root).expanduser()
    simulator_root = root / "user_data_ui" / "simDir" / "simulator0"
    settings_root = simulator_root / "user_data" / "settings"
    robot_urdf = _find_one(
        list(settings_root.glob("generated_robot*_abs_path.urdf")),
        description="generated robot URDF",
    )
    robot_srdf = _find_one(
        list(settings_root.glob("generated_robot*_abs_path.srdf")),
        description="generated robot SRDF",
    )
    scene_urdf = settings_root / "user_scene_abs_path.urdf"
    param = _find_one(
        list(simulator_root.glob("*/arm_driver_param.xml")) + list(settings_root.glob("*/arm_driver_param.xml")),
        description="arm driver parameter file",
    )
    return {
        "robot_urdf": _relative_to_studio_root(robot_urdf, root),
        "robot_srdf": _relative_to_studio_root(robot_srdf, root),
        "scene_urdf": _relative_to_studio_root(scene_urdf, root),
        "param": _relative_to_studio_root(param, root),
    }


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--studio-root", type=Path, default=flexiv_runtime.STUDIO_ROOT)
    parser.add_argument("--robot-urdf", default=None)
    parser.add_argument("--robot-srdf", default=None)
    parser.add_argument("--scene-urdf", default=None)
    parser.add_argument("--param", default=None)
    parser.add_argument("--group-state", default="home")
    args = parser.parse_args(argv)
    discovered = discover_simulation_assets(args.studio_root)
    args.robot_urdf = args.robot_urdf or discovered["robot_urdf"]
    args.robot_srdf = args.robot_srdf or discovered["robot_srdf"]
    args.scene_urdf = args.scene_urdf or discovered["scene_urdf"]
    args.param = args.param or discovered["param"]
    return args


def build_command(args: argparse.Namespace) -> list[str]:
    return [
        "./FlexivSimulation",
        "--robot_urdf",
        str(args.robot_urdf),
        "--robot_srdf",
        str(args.robot_srdf),
        "--scene_urdf",
        str(args.scene_urdf),
        "--param",
        str(args.param),
        "--group_state",
        str(args.group_state),
    ]


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    pid, stdout_path, stderr_path = flexiv_runtime.start_background(
        build_command(args),
        cwd=args.studio_root,
        log_prefix="flexiv_simulation",
        env=flexiv_runtime.studio_env(args.studio_root),
    )
    flexiv_runtime.print_started("FLEXIV_SIMULATION", pid, stdout_path, stderr_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
